name: eeg_thesis_v1
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - mne=1.10.2
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - matplotlib
  - seaborn
  - jupyterlab
  - ipykernel
  - pytorch
  - torchvision
  - torchaudio
  - cpuonly # Change to 'pytorch-cuda=11.8' etc if you have a GPU
  - pip:
    - hampel
    - mne-denoise
    - mne-icalabel  # For automated ICA labeling
    - yasa           # For sleep EEG analysis
    - pyod           # For outlier/spike detection
